apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-redis
  labels:
    app: sre-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-redis
  template:
    metadata:
      labels:
        app: sre-redis
    spec:
      containers:
      - name: sre-redis
        image: "docker.io/redis"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379