name: CI/CD
on: [push, workflow_dispatch]

jobs:
  build:
    name: Build App image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: keerthanyadav/test-repo
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          addLatest: True

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}
          source: "k8s-deployment/deploy-app.yml,k8s-deployment/deploy-redis.yml,k8s-deployment/service.yml"
          target: "~/deployments"
  
      - name: Run SSH command
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            kubectl apply -f ~/deployments/k8s-deployment/deploy-redis.yml
            kubectl apply -f ~/deployments/k8s-deployment/deploy-app.yml
            kubectl apply -f ~/deployments/k8s-deployment/service.yml
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWORD}}
          

